//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENT
    {
        public string AGENTID { get; set; }
        public string AGENTNAME { get; set; }
        public string AGENTADDRESS { get; set; }
        public string AGENTEMAIL { get; set; }
        public string AGENTPHONE { get; set; }
        public string AGENTPASSWORD { get; set; }
    }
}
