//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public string ORDERID { get; set; }
        public string AGENTID { get; set; }
        public string DELIVERYNOTE_ID { get; set; }
        public Nullable<System.DateTime> ORDERDATE { get; set; }
        public string ORDERSTATUS { get; set; }
        public string PAYMENTSTATUS { get; set; }
        public string PAYMENTMETHOD { get; set; }
    }
}
