//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_DETAIL
    {
        public string ODETAIL_ID { get; set; }
        public string ORDERID { get; set; }
        public string PRODUCTID { get; set; }
        public Nullable<int> BUYQUANTITY { get; set; }
    }
}
