//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public string PRODUCTID { get; set; }
        public string PRONAME { get; set; }
        public Nullable<decimal> PROPRICE { get; set; }
        public string PROORIGIN { get; set; }
        public Nullable<int> PROQUANTITY { get; set; }
        public string PROTYPE { get; set; }
        public string PROBRAND { get; set; }
        public string PRODESCRIPTION { get; set; }
        public Nullable<System.DateTime> USEDATE { get; set; }
        public Nullable<int> HASSOLD { get; set; }
        public string PROIMG { get; set; }
    }
}
